#!/bin/bash
eval $(maws li "Team 03")
cd /Users/dcmennell/clusters/konvoy/awsDemo/BLUE/konvoy_v0.3.0/
rm -rf cluster.yaml runs/ state/ AWS-ssh.pem AWS-ssh.pub konvoy_v0.3.0-ssh.pem konvoy_v0.3.0-ssh.pub admin.conf
./konvoy up -y
export KUBECONFIG=/Users/dcmennell/clusters/konvoy/awsDemo/BLUE/konvoy_v0.3.0/admin.conf
open https://$(./konvoy get ops-portal | grep Username | awk '{print $2}'):$(./konvoy get ops-portal | grep Password | awk '{print $2}')@$(./konvoy get ops-portal | grep https | cut -f3 -d\/)
#kubectl apply -f ./microservices-demo-master/release/kubernetes-manifests.yaml
kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/master/release/kubernetes-manifests.yaml
$SHELL
source ~/.bash_profile