kind: StoragePoolClaim
apiVersion: openebs.io/v1alpha1
metadata:
  name: cstor-disk-pool
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-disk-pool
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
    - blockdevice-053952b9310bc02680a34e241580ad3a
    - blockdevice-a4fdf32b095cdd2ebe9827d403c02586
    - blockdevice-c99a716407d7622e26f2eec2a387a141
    - blockdevice-ec662747f2e10dfcb3f82850b3b4723d